import {
  HiOutlineExclamationCircle,
  HiOutlineDotsVertical,
  HiOutlineDocumentText,
  HiOutlineDocumentAdd,
  HiOutlineLockClosed,
  HiOutlineFolderAdd,
  HiOutlineLockOpen,
  HiOutlineDatabase,
  HiOutlineTemplate,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineMailOpen,
  HiOutlineUserAdd,
  HiOutlineSearch,
  HiOutlineLogout,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineCheck,
  HiOutlineClock,
  HiOutlineBell,
  HiOutlineMail,
  HiOutlineSave,
  HiOutlineCog,
  HiOutlineEye,
  HiPaperClip,
  HiHashtag,
  HiHeart,
  HiMenu,
  HiLink,
} from "react-icons/hi";
import {
  HiOutlineChatBubbleLeftRight,
  HiOutlineUserCircle,
  HiDevicePhoneMobile,
  HiOutlineUserGroup,
  HiOutlineFaceSmile,
  HiOutlineUser,
  HiOutlineStar,
} from "react-icons/hi2";
import {
  IoChevronDownOutline,
  IoMailUnreadOutline,
  IoArrowBackOutline,
  IoWarningOutline,
  IoChevronUp,
  IoClose,
  IoSend,
} from "react-icons/io5";
import { LuGoal } from "react-icons/lu";
import {
  CgCornerUpLeft,
  CgCornerDoubleUpLeft,
  CgCornerUpRight,
} from "react-icons/cg";
import { TbTemplate, TbMailPlus } from "react-icons/tb";
import {
  MdOutlineInsertEmoticon,
  MdOutlineMarkChatUnread,
  MdOutlineEventNote,
  MdOutlinePlace,
  MdTitle,
} from "react-icons/md";
import { BsFilter, BsTelephone } from "react-icons/bs";
import {
  AiOutlineIdcard,
  AiOutlineCar,
  AiOutlinePlus,
  AiOutlinePaperClip,
} from "react-icons/ai";
import { BiMailSend, BiBellPlus } from "react-icons/bi";
import { PiRobot, PiFolderSimpleDashed } from "react-icons/pi";

export {
  HiOutlineChatBubbleLeftRight,
  HiOutlineExclamationCircle,
  MdOutlineMarkChatUnread,
  MdOutlineInsertEmoticon,
  HiOutlineDotsVertical,
  HiOutlineDocumentText,
  CgCornerDoubleUpLeft,
  HiOutlineDocumentAdd,
  PiFolderSimpleDashed,
  IoChevronDownOutline,
  IoMailUnreadOutline,
  HiOutlineUserCircle,
  HiDevicePhoneMobile,
  HiOutlineLockClosed,
  MdOutlineEventNote,
  IoArrowBackOutline,
  HiOutlineFolderAdd,
  AiOutlinePaperClip,
  HiOutlineUserGroup,
  HiOutlineFaceSmile,
  HiOutlineLockOpen,
  HiOutlineDatabase,
  HiOutlineTemplate,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineMailOpen,
  HiOutlineUserAdd,
  IoWarningOutline,
  CgCornerUpRight,
  HiOutlineSearch,
  HiOutlineLogout,
  HiOutlinePencil,
  AiOutlineIdcard,
  HiOutlineClock,
  MdOutlinePlace,
  HiOutlineTrash,
  HiOutlineCheck,
  CgCornerUpLeft,
  HiOutlineStar,
  AiOutlinePlus,
  HiOutlineUser,
  HiOutlineBell,
  HiOutlineMail,
  HiOutlineSave,
  AiOutlineCar,
  HiOutlineCog,
  HiOutlineEye,
  IoChevronUp,
  BsTelephone,
  HiPaperClip,
  BiBellPlus,
  TbTemplate,
  TbMailPlus,
  BiMailSend,
  HiHashtag,
  BsFilter,
  PiRobot,
  MdTitle,
  IoClose,
  HiHeart,
  LuGoal,
  HiLink,
  HiMenu,
  IoSend,
};
