import {
  HiOutlineExclamationCircle,
  HiOutlineDotsVertical,
  HiOutlineDocumentText,
  HiOutlineLockClosed,
  HiOutlineFolderAdd,
  HiOutlineLockOpen,
  HiOutlineDatabase,
  HiOutlineTemplate,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineMailOpen,
  HiOutlineUserAdd,
  HiOutlineSearch,
  HiOutlineLogout,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineCheck,
  HiOutlineClock,
  HiOutlineBell,
  HiOutlineMail,
  HiOutlineSave,
  HiOutlineCog,
  HiOutlineEye,
  HiHashtag,
  HiLink,
} from "react-icons/hi";
import {
  HiOutlineChatBubbleLeftRight,
  HiOutlineUserCircle,
  HiOutlineUser,
  HiDevicePhoneMobile,
  HiOutlineStar,
} from "react-icons/hi2";
import {
  IoClose,
  IoArrowBackOutline,
  IoMailUnreadOutline,
  IoWarningOutline,
} from "react-icons/io5";
import { LuGoal } from "react-icons/lu";
import {
  CgCornerUpLeft,
  CgCornerDoubleUpLeft,
  CgCornerUpRight,
} from "react-icons/cg";
import { TbTemplate, TbMailPlus } from "react-icons/tb";
import {
  MdOutlineEventNote,
  MdOutlinePlace,
  MdTitle,
  MdOutlineInsertEmoticon,
} from "react-icons/md";
import { BsFilter } from "react-icons/bs";
import { AiOutlineIdcard, AiOutlineCar, AiOutlinePlus } from "react-icons/ai";
import { BiMailSend, BiBellPlus } from "react-icons/bi";
import { PiRobot, PiFolderSimpleDashed } from "react-icons/pi";

export {
  HiOutlineChatBubbleLeftRight,
  HiOutlineExclamationCircle,
  MdOutlineInsertEmoticon,
  HiOutlineDotsVertical,
  HiOutlineDocumentText,
  CgCornerDoubleUpLeft,
  PiFolderSimpleDashed,
  IoMailUnreadOutline,
  HiOutlineUserCircle,
  HiDevicePhoneMobile,
  HiOutlineLockClosed,
  MdOutlineEventNote,
  IoArrowBackOutline,
  HiOutlineFolderAdd,
  HiOutlineLockOpen,
  HiOutlineDatabase,
  HiOutlineTemplate,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineMailOpen,
  HiOutlineUserAdd,
  IoWarningOutline,
  CgCornerUpRight,
  HiOutlineSearch,
  HiOutlineLogout,
  HiOutlinePencil,
  AiOutlineIdcard,
  HiOutlineClock,
  MdOutlinePlace,
  HiOutlineTrash,
  HiOutlineCheck,
  CgCornerUpLeft,
  HiOutlineStar,
  AiOutlinePlus,
  HiOutlineUser,
  HiOutlineBell,
  HiOutlineMail,
  HiOutlineSave,
  AiOutlineCar,
  HiOutlineCog,
  HiOutlineEye,
  BiBellPlus,
  TbTemplate,
  TbMailPlus,
  BiMailSend,
  HiHashtag,
  BsFilter,
  PiRobot,
  MdTitle,
  IoClose,
  LuGoal,
  HiLink,
};
